---
title: "GCD Quiz 4"
author: "Frank Shuster"
date: "Wednesday, November 05, 2014"
output: word_document
---

## Quiz 4 - Getting and Cleaning Data

### Question 1

The American Community Survey distributes downloadable data about United States communities. Download the 2006 microdata survey about housing for the state of Idaho using download.file() from here: 

https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv 

and load the data into R. The code book, describing the variable names is here: 

https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FPUMSDataDict06.pdf 

Apply strsplit() to split all the names of the data frame on the characters "wgtp". What is the value of the 123 element of the resulting list?

### Answer

""  "15"

### R Code

```
if(!file.exists("./data")){dir.create("./data")}
fileURL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv"
download.file(fileURL, destfile = "./data/acsdata.csv")

file = "acsdata.csv"
acsdata <-  read.csv(file, header = TRUE, stringsAsFactors = FALSE)

splitNames <- strsplit(names(acsdata),"wgtp")

splitNames[123]
```

### Question 2

Load the Gross Domestic Product data for the 190 ranked countries in this data set: 

https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv 

Remove the commas from the GDP numbers in millions of dollars and average them. What is the average? 

Original data sources: http://data.worldbank.org/data-catalog/GDP-ranking-table

### Answer

377652.4

### R Code

```
if(!file.exists("./data")){dir.create("./data")}
fileURL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv"
download.file(fileURL, destfile = "./data/FGDP.csv")
file = "./data/FGDP.csv"
FGDP <-  read.csv(file, header = TRUE, stringsAsFactors = FALSE)

column.names <- c("CountryCode", "GDPRank","X.1","CountryName", "GDP", "X.4", "X5" )

FGDP <- FGDP[5:nrow(FGDP),]
FGDP <- FGDP[1:190,]

FGDPClean <- data.frame(FGDP$X, FGDP$Gross.domestic.product.2012, FGDP$X.3)
colnames(FGDPClean) <- c("CountryCode", "GDPRank", "GDP")

FGDPClean$GDP <- as.numeric(gsub(",","",FGDPClean$GDP))

GDPmean <- mean(FGDPClean$GDP)
```
### Question 3

In the data set from Question 2 what is a regular expression that would allow you to count the number of countries whose name begins with "United"? Assume that the variable with the country names in it is named countryNames. How many countries begin with United?

### Answser

3

### R Code

```
grep("^United",FGDP$X.2)
```
### Question 4

Load the Gross Domestic Product data for the 190 ranked countries in this data set: 

https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv 

Load the educational data from this data set: 

https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv 

Match the data based on the country shortcode. Of the countries for which the end of the fiscal year is available, how many end in June? 

Original data sources: 
http://data.worldbank.org/data-catalog/GDP-ranking-table 
http://data.worldbank.org/data-catalog/ed-stats

### Answer

13

### R Code
```
if(!file.exists("./data")){dir.create("./data")}
fileURL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv"
download.file(fileURL, destfile = "./data/fedstats.csv")
file = "./data/fedstats.csv"
fedstats <-  read.csv(file, header = TRUE, stringsAsFactors = FALSE)

FGDPClean$CountryCode <- as.character(FGDPClean$CountryCode)
FGDPfeststatsmerge <- merge(FGDPClean, fedstats, by = "CountryCode")

length(grep("[Ff]iscal [Yy]ear [Ee]nd: [Jj]une",FGDPfeststatsmerge$Special.Notes))
```
### Question 5

You can use the quantmod (http://www.quantmod.com/) package to get historical stock prices for publicly traded companies on the NASDAQ and NYSE. Use the following code to download data on Amazon's stock price and get the times the data was sampled.
```
library(quantmod)
amzn = getSymbols("AMZN",auto.assign=FALSE)
sampleTimes = index(amzn) 
```
How many values were collected in 2012? How many values were collected on Mondays in 2012?

### Answer

250, 47

### R Code
```
library(quantmod)
amzn <- getSymbols("AMZN",auto.assign=FALSE)
sampleTimes <- index(amzn) 

sampleTimesNew <- format(sampleTimes,"%A %B %d %Y")

length(grep("2012$",sampleTimesNew))
length(grep("^Monday.*2012$",sampleTimesNew))
```
